grails-app/domain/stackoverflow/Tag.groovy
package stackoverflow

class Tag {
	
	String	label

    static constraints = {
    }
	
	static hasMany = [subjects: Subject]
	
	static belongsTo = Subject
}

grails-app/controllers/stackoverflow/TagController.groovy
package stackoverflow

import org.apache.log4j.Logger

import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController {

    Logger logger = Logger.getLogger(this.class)

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def index(Integer max) {
        logger.trace("Begin of index method")

        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
    def show(Tag tagInstance) {
        logger.trace("Begin of show method")

        respond tagInstance
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def create() {
        logger.trace("Begin of create method")

        respond new Tag(params)
    }

	
	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def save(Tag tagInstance) {
        logger.trace("Begin of save method")

        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

	
	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def edit(Tag tagInstance) {
        logger.trace("Begin of edit method")

        respond tagInstance
    }

	
	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def update(Tag tagInstance) {
        logger.trace("Begin of update method")

        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

	
	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def delete(Tag tagInstance) {
        logger.trace("Begin of delete method")

        if (tagInstance == null) {
            notFound()
            return
        }

        tagInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    protected void notFound() {
        logger.trace("Begin of notFound method")

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tag/_form.gsp
<%@ page import="stackoverflow.Tag" %>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'label', 'error')} required">
	<label for="label">
		<g:message code="tag.label" default="Label" />
		<span class="required-indicator">*</span>
	</label>

	<g:textField name="label" required="" value="${tagInstance?.label}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'subjects', 'error')} ">
	<label>
		<g:message code="subjects.label" default="Subjects" />
	</label>
</div>

grails-app/views/tag/create.gsp
<%@ page import="org.springframework.validation.FieldError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#create-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="create-tag" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${tagInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${tagInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:tagInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tag/edit.gsp
<%@ page import="stackoverflow.Tag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#edit-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="edit-tag" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${tagInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${tagInstance}" var="error">
						<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:tagInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${tagInstance?.version}" />

				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tag/index.gsp
<%@ page import="stackoverflow.Tag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#list-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="list-tag" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<table>
				<thead>
					<tr>
						<g:sortableColumn property="label" title="${message(code: 'tag.label', default: 'Tag')}" />
					</tr>
				</thead>

				<tbody>
					<g:each in="${tagInstanceList}" status="i" var="tagInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<td><g:link action="show" id="${tagInstance.id}">${fieldValue(bean: tagInstance, field: "label")}</g:link></td>
						</tr>
					</g:each>
				</tbody>
			</table>

			<div class="pagination">
				<g:paginate total="${tagInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/tag/show.gsp
<%@ page import="stackoverflow.Tag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#show-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="show-tag" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list tag">
				<g:if test="${tagInstance?.label}">
					<li class="fieldcontain">
						<span id="label-label" class="property-label"><g:message code="tag.label" default="Tag" /></span>
						<span class="property-value" aria-labelledby="label-label"><g:fieldValue bean="${tagInstance}" field="label"/></span>
					</li>
				</g:if>
			
				<g:if test="${tagInstance?.subjects}">
					<li class="fieldcontain">
						<span id="subjects-label" class="property-label"><g:message code="subjects.label" default="Subjects" /></span>
							<g:each in="${tagInstance.subjects}" var="s">
								<span class="property-value" aria-labelledby="subjects-label">
									<g:link controller="subject" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link>
								</span>
							</g:each>
					</li>
				</g:if>
			</ol>

			<g:form url="[resource:tagInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${tagInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>