grails-app/domain/stackoverflow/Answer.groovy
package stackoverflow

class Answer {
	
	String	content
	Date dateCreated
	Date lastUpdated
	static mapping = {
		autoTimestamp true
		sort "vote"
		answerComments sort:"dateCreated"
	}

	int	vote

    static constraints = {
    }
	
	
	static belongsTo = [subject: Subject, author: SecUser]
	
	static hasMany = [answerComments: Comment]

}

grails-app/controllers/stackoverflow/AnswerController.groovy
package stackoverflow

import org.apache.log4j.Logger

import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AnswerController {
    Logger logger = Logger.getLogger(this.class);

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
	
	def answerService

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def index(Integer max) {
        logger.trace("Begin of index method")

        params.max = Math.min(max ?: 10, 100)
        respond Answer.list(params), model:[answerInstanceCount: Answer.count()]
    }
	
	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
    def show(Answer answerInstance) {
        logger.trace("Showing " + answerInstance.toString())

        respond answerInstance
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    def create() {
        logger.trace("Creating a new Answer")

        respond new Answer(params)
    }	

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    @Transactional
    def save(Answer answerInstance) {
        logger.trace("Saving answer " + answerInstance?.id)

        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'create'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*' { respond answerInstance, [status: CREATED] }
        }
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    def edit(Answer answerInstance) {
        logger.trace("Editing " + answerInstance)

		def user = SecUser.get(springSecurityService.principal.id)

		if (answerInstance.author.id == user.id){
        	respond answerInstance
		}
		else{
            logger.debug(user.id + " cannot edit " + answerInstance)
            notFound()
		}
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    @Transactional
    def update(Answer answerInstance) {
        logger.trace("Updating answer " + answerInstance?.id)

        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'edit'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*'{ respond answerInstance, [status: OK] }
        }
    }

    @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def delete(Answer answerInstance) {
        logger.trace("Deleting answer " + answerInstance?.id)

        if (answerInstance == null) {
            notFound()
            return
        }

        answerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        logger.trace("answerInstance not found")
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'answer.label', default: 'Answer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }	
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	def createComment(Answer answerInstance){
        logger.trace("Creating comment on " + answerInstance.toString())

		respond answerInstance
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def updateWithoutRedirect (Answer answerInstance) {
        logger.trace("Updating " + answerInstance.toString() + " without redirect")

		if (answerInstance == null) {
			notFound()
			return
		}

		if (answerInstance.hasErrors()) {
			respond answerInstance.errors, view:'edit'
			return
		}

		answerInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
				redirect answerInstance.subject
			}
			'*'{ respond answerInstance, [status: OK] }
		}
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def upVote (Answer answerInstance){
        logger.trace(answerInstance.toString() + " upVote")

		println params
		answerService.upVote(answerInstance)
		updateWithoutRedirect(answerInstance);
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def downVote (Answer answerInstance){
        logger.trace(answerInstance.toString() + " downVote")

        answerService.downVote(answerInstance)
		updateWithoutRedirect(answerInstance);
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def addComment(Answer answerInstance){
		Comment newComment = new Comment(params);
		Answer persistedAnswer = Answer.get(params.answer.id)

        logger.trace("[" + persistedAnswer + "] addComment " + newComment)

        newComment.save(failOnError: true)
		
		redirect action: "show", controller: "subject", id: persistedAnswer.subject.id
	}
}

grails-app/views/answer/_form.gsp
<%@ page import="stackoverflow.Subject; stackoverflow.Answer" %>

<%--<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'author', 'error')} required">--%>
<%--	<label for="author">--%>
<%--		<g:message code="answer.author.label" default="Author" />--%>
<%--		<span class="required-indicator">*</span>--%>
<%--	</label>--%>
<%--	<g:select id="author" name="author.id" from="${stackoverflow.User.list()}" optionKey="id" required="" value="${answerInstance?.author?.id}" class="many-to-one"/>--%>
<%----%>
<%--</div>--%>

<%--<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'comments', 'error')} ">--%>
<%--	<label for="comments">--%>
<%--		<g:message code="answer.comments.label" default="Comments" />--%>
<%--		--%>
<%--	</label>--%>
<%--	--%>
<%--<ul class="one-to-many">--%>
<%--<g:each in="${answerInstance?.comments?}" var="c">--%>
<%--    <li><g:link controller="comment" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></li>--%>
<%--</g:each>--%>
<%--<li class="add">--%>
<%--<g:link controller="comment" action="create" params="['answer.id': answerInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'comment.label', default: 'Comment')])}</g:link>--%>
<%--</li>--%>
<%--</ul>--%>
%{--</div>--}%

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'content', 'error')} required">
	<label for="content">
		<g:message code="content.label" default="Content" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="content" required="" value="${answerInstance?.content}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'subject', 'error')} required" style="display: none;">
	<label for="subject">
		<g:message code="subject.label" default="Subject" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="subject" name="subject.id" from="${Subject.list()}" optionKey="id" required="" value="${answerInstance?.subject?.id}" class="many-to-one"/>

</div>

<%--<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'vote', 'error')} required">--%>
<%--	<label for="vote">--%>
<%--		<g:message code="answer.vote.label" default="Vote" />--%>
<%--		<span class="required-indicator">*</span>--%>
<%--	</label>--%>
<%--	<g:field name="vote" type="number" value="${answerInstance.vote}" required=""/>--%>
<%----%>
<%--</div>--%>

grails-app/views/answer/create.gsp
<%@ page import="org.springframework.validation.FieldError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#create-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="create-answer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${answerInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${answerInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:answerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/answer/createComment.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>${answerInstance.subject.title}</title>
	</head>
	 
	<body>
		<div id="show-subject" class="content scaffold-show" role="main">
			<h1>${answerInstance.subject.title}</h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list subject">
				<li class="panel-body">
					<p>${answerInstance.content}</p>
					<div id="comments">
						<g:render template="/comment/commentsForAnswer" model="${['answerComments':answerInstance.answerComments]}"/>
					</div>
				</li>

				<li>
					<g:form name="addComment">
						<g:textArea name="content" placeholder="New comment" rows="5" id="textArea" class="form-control"/>
						<g:hiddenField name="answer.id" value="${answerInstance.id}" />
						<g:hiddenField name="author.id" value="${applicationContext.springSecurityService.currentUser.id}"/>
						<br/>
						<g:actionSubmit class="btn btn-success btn-flat" controller="answer" action="addComment" value="New comment"/>
					</g:form>	
				</li>
			</ol>
		</div>
	</body>
</html>

grails-app/views/answer/edit.gsp
<%@ page import="org.springframework.validation.FieldError; stackoverflow.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#edit-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="edit-answer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${answerInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${answerInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:answerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${answerInstance?.version}" />

				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/answer/index.gsp
<%@ page import="stackoverflow.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#list-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="list-answer" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<table>
				<thead>
					<tr>
						<%--<th><g:message code="answer.author.label" default="Author" /></th>--%>
						<g:sortableColumn property="content" title="${message(code: 'content.label', default: 'Content')}" />
						<g:sortableColumn property="dateCreated" title="${message(code: 'creationDate.label', default: 'Creation Date')}" />
						<th><g:message code="subject.label" default="Subject" /></th>
						<g:sortableColumn property="vote" title="${message(code: 'vote.label', default: 'Vote')}" />
					</tr>
				</thead>

				<tbody>
					<g:each in="${answerInstanceList}" status="i" var="answerInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<%--<td><g:link action="show" id="${answerInstance.id}">${fieldValue(bean: answerInstance, field: "author")}</g:link></td>--%>
							<td>${fieldValue(bean: answerInstance, field: "content")}</td>
							<td><g:formatDate date="${answerInstance.dateCreated}" /></td>
							<td>${fieldValue(bean: answerInstance, field: "subject")}</td>
							<td>${fieldValue(bean: answerInstance, field: "vote")}</td>
						</tr>
					</g:each>
				</tbody>
			</table>

			<div class="pagination">
				<g:paginate total="${answerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/answer/show.gsp
<%@ page import="stackoverflow.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-answer" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list answer">
			
<%--				<g:if test="${answerInstance?.author}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="author-label" class="property-label"><g:message code="answer.author.label" default="Author" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="author-label"><g:link controller="user" action="show" id="${answerInstance?.author?.id}">${answerInstance?.author?.encodeAsHTML()}</g:link></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
			
				<g:if test="${answerInstance?.answerComments}">
					<li class="fieldcontain">
						<span id="comments-label" class="property-label"><g:message code="comments.label" default="Comments" /></span>

						<g:each in="${answerInstance.answerComments}" var="c">
							<span class="property-value" aria-labelledby="comments-label"><g:link controller="comment" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></span>
						</g:each>
					</li>
				</g:if>
			
				<g:if test="${answerInstance?.content}">
					<li class="fieldcontain">
						<span id="content-label" class="property-label"><g:message code="content.label" default="Content" /></span>
						<span class="property-value" aria-labelledby="content-label"><g:fieldValue bean="${answerInstance}" field="content"/></span>
					</li>
				</g:if>
			
				<g:if test="${answerInstance?.dateCreated}">
					<li class="fieldcontain">
						<span id="dateCreated-label" class="property-label"><g:message code="creationDate.label" default="Creation Date" /></span>
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${answerInstance?.dateCreated}" /></span>
					</li>
				</g:if>
			
				<g:if test="${answerInstance?.subject}">
					<li class="fieldcontain">
						<span id="subject-label" class="property-label"><g:message code="subject.label" default="Subject" /></span>
						<span class="property-value" aria-labelledby="subject-label"><g:link controller="subject" action="show" id="${answerInstance?.subject?.id}">${answerInstance?.subject?.encodeAsHTML()}</g:link></span>
					</li>
				</g:if>
			
				<g:if test="${answerInstance?.vote}">
					<li class="fieldcontain">
						<span id="vote-label" class="property-label"><g:message code="vote.label" default="Vote" /></span>
						<span class="property-value" aria-labelledby="vote-label"><g:fieldValue bean="${answerInstance}" field="vote"/></span>
					</li>
				</g:if>
			</ol>

			<g:form url="[resource:answerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${answerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>