grails-app/domain/stackoverflow/Comment.groovy
package stackoverflow

class Comment {
	
   String	content
   Date dateCreated
   Date lastUpdated
   static mapping = {
      autoTimestamp true
	  sort "dateCreated"
   }

    static constraints = {
    }
	
	int vote
	
	static belongsTo = [answer: Answer, author: SecUser]

}

grails-app/controllers/stackoverflow/CommentController.groovy
package stackoverflow

import org.apache.log4j.Logger

import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CommentController {
    Logger logger = Logger.getLogger(this.class)

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
	
	def commentService

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def index(Integer max) {
        logger.trace("Begin of index method")

        params.max = Math.min(max ?: 10, 100)
        respond Comment.list(params), model:[commentInstanceCount: Comment.count()]
    }

	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
    def show(Comment commentInstance) {
        logger.trace("Show " + commentInstance.toString())

        respond commentInstance
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    def create() {
        logger.trace("Begin of create comment method")

        respond new Comment(params)
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    @Transactional
    def save(Comment commentInstance) {
        logger.trace("Save " + commentInstance.toString())

        if (commentInstance == null) {
            notFound()
            return
        }

        if (commentInstance.hasErrors()) {
            respond commentInstance.errors, view:'create'
            return
        }

        commentInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'comment.label', default: 'Comment'), commentInstance.id])
                redirect commentInstance
            }
            '*' { respond commentInstance, [status: CREATED] }
        }
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    def edit(Comment commentInstance) {
        logger.trace("Edit " + commentInstance.toString())

		def user = SecUser.get(springSecurityService.principal.id)
		if (commentInstance.author.id == user.id){
        	respond commentInstance
		}
		else{
            notFound()
		}
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    @Transactional
    def update(Comment commentInstance) {
        logger.trace("Update " + commentInstance.toString())

        if (commentInstance == null) {
            notFound()
            return
        }

        if (commentInstance.hasErrors()) {
            respond commentInstance.errors, view:'edit'
            return
        }

        commentInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'comment.label', default: 'Comment'), commentInstance.id])
                redirect commentInstance
            }
            '*'{ respond commentInstance, [status: OK] }
        }
    }
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def updateWithoutRedirect (Comment commentInstance) {
        logger.trace("Begin of updateWithoutRedirect method")

		if (commentInstance == null) {
			notFound()
			return
		}

		if (commentInstance.hasErrors()) {
			respond commentInstance.errors, view:'edit'
			return
		}

		commentInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'comment.label', default: 'Comment'), commentInstance.id])
				redirect commentInstance.answer.subject
			}
			'*'{ respond commentInstance, [status: OK] }
		}
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def upVote (Comment commentInstance){
        logger.trace("Begin of upVote comment " + commentInstance.toString())

		println params
		commentService.upVote(commentInstance)
		updateWithoutRedirect(commentInstance);
	}
	
	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
	@Transactional
	def downVote (Comment commentInstance){
        logger.trace("Begin of downVote comment " + commentInstance.toString())

		commentService.downVote(commentInstance)
		updateWithoutRedirect(commentInstance);
	}

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    @Transactional
    def delete(Comment commentInstance) {
        logger.trace("Begin of delete " + commentInstance.toString())

        if (commentInstance == null) {
            notFound()
            return
        }

        commentInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'comment.label', default: 'Comment'), commentInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        logger.trace("Begin of notFound method")

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'comment.label', default: 'Comment'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/comment/_commentsForAnswer.gsp
<g:if test="${answerComments?.size() > 0}">
	<strong id="comments-label" class="property-label"><g:message code="comments.label" default="Comments" /></strong>

	<ul class="list-unstyled well well-sm">
		<g:each var="comment" in="${answerComments}" >
			<li class="">
				<g:form url="[resource:comment]" controller="comment">
					<span>
						<g:actionSubmit value="-" action="downVote" class="btn btn-danger btn-xs"/>
						<strong>${comment.vote}</strong>
						<g:actionSubmit value="+" action="upVote" class="btn btn-success btn-xs"/>
					</span>
				</g:form>

				<small><g:link id="${comment.author.id}" controller="secUser" action="show">${comment.author.username}</g:link> - ${comment.lastUpdated}</small>

				<p>${comment.content}</p>
			</li>
		</g:each>
	</ul>
</g:if>

grails-app/views/comment/_form.gsp
<%@ page import="stackoverflow.Comment" %>

<div class="fieldcontain ${hasErrors(bean: commentInstance, field: 'content', 'error')} required">
	<label for="content">
		<g:message code="content.label" default="Content" />
		<span class="required-indicator">*</span>
	</label>

	<g:textField name="content" required="" value="${commentInstance?.content}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: commentInstance, field: 'creationDate', 'error')} required">
	<label for="creationDate">
		<g:message code="creationDate.label" default="Creation Date" />
		<span class="required-indicator">*</span>
	</label>

	<g:datePicker name="creationDate" precision="day"  value="${commentInstance?.creationDate}"  />
</div>

grails-app/views/comment/create.gsp
<%@ page import="org.springframework.validation.FieldError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'comments.label', default: 'Comment')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#create-comment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="create-comment" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${commentInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${commentInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:commentInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/comment/edit.gsp
<%@ page import="org.springframework.validation.FieldError; stackoverflow.Comment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'comment.label', default: 'Comment')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#edit-comment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="edit-comment" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${commentInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${commentInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:commentInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${commentInstance?.version}" />

				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/comment/index.gsp
<%@ page import="stackoverflow.Comment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'comment.label', default: 'Comment')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#list-comment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="list-comment" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<table>
				<thead>
					<tr>
						<g:sortableColumn property="content" title="${message(code: 'content.label', default: 'Content')}" />
						<g:sortableColumn property="creationDate" title="${message(code: 'creationDate.label', default: 'Creation Date')}" />
					</tr>
				</thead>

				<tbody>
					<g:each in="${commentInstanceList}" status="i" var="commentInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<td><g:link action="show" id="${commentInstance.id}">${fieldValue(bean: commentInstance, field: "content")}</g:link></td>
							<td><g:formatDate date="${commentInstance.creationDate}" /></td>
						</tr>
					</g:each>
				</tbody>
			</table>

			<div class="pagination">
				<g:paginate total="${commentInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/comment/show.gsp
<%@ page import="stackoverflow.Comment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'comment.label', default: 'Comment')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#show-comment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="show-comment" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list comment">
				<g:if test="${commentInstance?.content}">
					<li class="fieldcontain">
						<span id="content-label" class="property-label"><g:message code="content.label" default="Content" /></span>
						<span class="property-value" aria-labelledby="content-label"><g:fieldValue bean="${commentInstance}" field="content"/></span>
					</li>
				</g:if>
			
				<g:if test="${commentInstance?.creationDate}">
					<li class="fieldcontain">
						<span id="creationDate-label" class="property-label"><g:message code="creationDate.label" default="Creation Date" /></span>
						<span class="property-value" aria-labelledby="creationDate-label"><g:formatDate date="${commentInstance?.creationDate}" /></span>
					</li>
				</g:if>
			</ol>

			<g:form url="[resource:commentInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${commentInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>