grails-app/domain/stackoverflow/SecUser.groovy
package stackoverflow

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class SecUser implements Serializable {

	private static final long serialVersionUID = 1

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
	
	
	static hasMany = [userComments: Comment, userAnswers: Answer, userSubjects: Subject]

	SecUser(String username, String password) {
		this()
		this.username = username
		this.password = password
	}

	Set<SecRole> getAuthorities() {
		SecUserSecRole.findAllBySecUser(this)*.secRole
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}
}

grails-app/controllers/stackoverflow/SecUserController.groovy
package stackoverflow

import org.apache.log4j.Logger

import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SecUserController {

    Logger logger = Logger.getLogger(this.class)
	
	def springSecurityService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def index(Integer max) {
        logger.trace("Begin of index method")

        params.max = Math.min(max ?: 10, 100)
        respond SecUser.list(params), model:[secUserInstanceCount: SecUser.count()]
    }

	@Secured(['IS_AUTHENTICATED_REMEMBERED'])
    def show(SecUser secUserInstance) {
        logger.trace("Begin of show method")

        respond secUserInstance
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def create() {
        logger.trace("Begin of create method")

        respond new SecUser(params)
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def save(SecUser secUserInstance) {
        logger.trace("Begin of save method")

        if (secUserInstance == null) {
            notFound()
            return
        }

        if (secUserInstance.hasErrors()) {
            respond secUserInstance.errors, view:'create'
            return
        }

        secUserInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'secUser.label', default: 'SecUser'), secUserInstance.id])
                redirect secUserInstance
            }
            '*' { respond secUserInstance, [status: CREATED] }
        }
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    def edit(SecUser secUserInstance) {
        logger.trace("Begin of edit method")

		SecUser currentLoggedInUser = springSecurityService.getCurrentUser();
		if (secUserInstance.id == currentLoggedInUser.id)
        	respond secUserInstance
		else
			render(status: 401, text: g.message(code: "unauthorized"))
    }

    @Transactional
    def update(SecUser secUserInstance) {
        logger.trace("Begin of update method")

        if (secUserInstance == null) {
            notFound()
            return
        }

        if (secUserInstance.hasErrors()) {
            respond secUserInstance.errors, view:'edit'
            return
        }

        secUserInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'secUser.label', default: 'SecUser'), secUserInstance.id])
                redirect secUserInstance
            }
            '*'{ respond secUserInstance, [status: OK] }
        }
    }

	@Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
    @Transactional
    def delete(SecUser secUserInstance) {
        logger.trace("Begin of delete method")

        if (secUserInstance == null) {
            notFound()
            return
        }

        secUserInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'secUser.label', default: 'SecUser'), secUserInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        logger.trace("Begin of notFound method")

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secUser.label', default: 'SecUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/secUser/_form.gsp
<%@ page import="stackoverflow.SecUser" %>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="secUser.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>

	<g:textField name="username" required="" value="${secUserInstance?.username}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="secUser.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>

	<g:textField name="password" required="" value="${secUserInstance?.password}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'accountExpired', 'error')} ">
	<label for="accountExpired">
		<g:message code="secUser.accountExpired.label" default="Account Expired" />
	</label>

	<g:checkBox name="accountExpired" value="${secUserInstance?.accountExpired}" />
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'accountLocked', 'error')} ">
	<label for="accountLocked">
		<g:message code="secUser.accountLocked.label" default="Account Locked" />
	</label>

	<g:checkBox name="accountLocked" value="${secUserInstance?.accountLocked}" />
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'enabled', 'error')} ">
	<label for="enabled">
		<g:message code="secUser.enabled.label" default="Enabled" />
	</label>

	<g:checkBox name="enabled" value="${secUserInstance?.enabled}" />
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'passwordExpired', 'error')} ">
	<label for="passwordExpired">
		<g:message code="secUser.passwordExpired.label" default="Password Expired" />
	</label>

	<g:checkBox name="passwordExpired" value="${secUserInstance?.passwordExpired}" />
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'userAnswers', 'error')} ">
	<label>
		<g:message code="secUser.userAnswers.label" default="User Answers" />
	</label>
	
	<ul class="one-to-many">
		<g:each in="${secUserInstance?.userAnswers?}" var="u">
			<li><g:link controller="answer" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></li>
		</g:each>

		<li class="add">
			<g:link controller="answer" action="create" params="['secUser.id': secUserInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'answer.label', default: 'Answer')])}</g:link>
		</li>
	</ul>
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'userComments', 'error')} ">
	<label>
		<g:message code="secUser.userComments.label" default="User Comments" />
	</label>
	
	<ul class="one-to-many">
		<g:each in="${secUserInstance?.userComments?}" var="u">
			<li><g:link controller="comment" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></li>
		</g:each>

		<li class="add">
			<g:link controller="comment" action="create" params="['secUser.id': secUserInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'comment.label', default: 'Comment')])}</g:link>
		</li>
	</ul>
</div>

<div class="fieldcontain ${hasErrors(bean: secUserInstance, field: 'userSubjects', 'error')} ">
	<label>
		<g:message code="secUser.userSubjects.label" default="User Subjects" />
	</label>
	
	<ul class="one-to-many">
		<g:each in="${secUserInstance?.userSubjects?}" var="u">
			<li><g:link controller="subject" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></li>
		</g:each>

		<li class="add">
			<g:link controller="subject" action="create" params="['secUser.id': secUserInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'subject.label', default: 'Subject')])}</g:link>
		</li>
	</ul>
</div>

grails-app/views/secUser/create.gsp
<%@ page import="org.springframework.validation.FieldError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#create-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="create-secUser" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${secUserInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${secUserInstance}" var="error">
						<li <g:if test="${error in FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:secUserInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secUser/edit.gsp
<%@ page import="stackoverflow.SecUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#edit-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="edit-secUser" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${secUserInstance}">
				<ul class="errors" role="alert">
					<g:eachError bean="${secUserInstance}" var="error">
						<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
							<g:message error="${error}"/>
						</li>
					</g:eachError>
				</ul>
			</g:hasErrors>

			<g:form url="[resource:secUserInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${secUserInstance?.version}" />

				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secUser/index.gsp
<%@ page import="stackoverflow.SecUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#list-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>

		<div id="list-secUser" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<table>
				<thead>
					<tr>
						<g:sortableColumn property="username" title="${message(code: 'secUser.username.label', default: 'Username')}" />
						<g:sortableColumn property="password" title="${message(code: 'secUser.password.label', default: 'Password')}" />
						<g:sortableColumn property="accountExpired" title="${message(code: 'secUser.accountExpired.label', default: 'Account Expired')}" />
						<g:sortableColumn property="accountLocked" title="${message(code: 'secUser.accountLocked.label', default: 'Account Locked')}" />
						<g:sortableColumn property="enabled" title="${message(code: 'secUser.enabled.label', default: 'Enabled')}" />
						<g:sortableColumn property="passwordExpired" title="${message(code: 'secUser.passwordExpired.label', default: 'Password Expired')}" />
					</tr>
				</thead>

				<tbody>
					<g:each in="${secUserInstanceList}" status="i" var="secUserInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<td><g:link action="show" id="${secUserInstance.id}">${fieldValue(bean: secUserInstance, field: "username")}</g:link></td>
							<td>${fieldValue(bean: secUserInstance, field: "password")}</td>
							<td><g:formatBoolean boolean="${secUserInstance.accountExpired}" /></td>
							<td><g:formatBoolean boolean="${secUserInstance.accountLocked}" /></td>
							<td><g:formatBoolean boolean="${secUserInstance.enabled}" /></td>
							<td><g:formatBoolean boolean="${secUserInstance.passwordExpired}" /></td>
						</tr>
					</g:each>
				</tbody>
			</table>

			<div class="pagination">
				<g:paginate total="${secUserInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/secUser/show.gsp
<%@ page import="stackoverflow.SecUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>

	<body>
		<a href="#show-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="show-secUser" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list secUser">
				<g:if test="${secUserInstance?.username}">
					<li class="fieldcontain">
						<span id="username-label" class="property-label"><g:message code="secUser.username.label" default="Username" /></span>
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${secUserInstance}" field="username"/></span>
					</li>
				</g:if>
			
<%--				<g:if test="${secUserInstance?.password}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="password-label" class="property-label"><g:message code="secUser.password.label" default="Password" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${secUserInstance}" field="password"/></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
<%--			--%>
<%--				<g:if test="${secUserInstance?.accountExpired}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="accountExpired-label" class="property-label"><g:message code="secUser.accountExpired.label" default="Account Expired" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="accountExpired-label"><g:formatBoolean boolean="${secUserInstance?.accountExpired}" /></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
<%--			--%>
<%--				<g:if test="${secUserInstance?.accountLocked}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="accountLocked-label" class="property-label"><g:message code="secUser.accountLocked.label" default="Account Locked" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="accountLocked-label"><g:formatBoolean boolean="${secUserInstance?.accountLocked}" /></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
<%--			--%>
<%--				<g:if test="${secUserInstance?.enabled}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="enabled-label" class="property-label"><g:message code="secUser.enabled.label" default="Enabled" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${secUserInstance?.enabled}" /></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
<%--			--%>
<%--				<g:if test="${secUserInstance?.passwordExpired}">--%>
<%--				<li class="fieldcontain">--%>
<%--					<span id="passwordExpired-label" class="property-label"><g:message code="secUser.passwordExpired.label" default="Password Expired" /></span>--%>
<%--					--%>
<%--						<span class="property-value" aria-labelledby="passwordExpired-label"><g:formatBoolean boolean="${secUserInstance?.passwordExpired}" /></span>--%>
<%--					--%>
<%--				</li>--%>
<%--				</g:if>--%>
			
				<g:if test="${secUserInstance?.userSubjects}">
					<li class="fieldcontain">
						<h2 id="userSubjects-label"><g:message code="secUser.userSubjects.label" default="User Subjects" /></h2>

						<div class="well">
							<ul class="list-unstyled homeSubjectList">
								<g:each in="${secUserInstance.userSubjects}" var="subject">
									<li class="homeSubjectListItem">
										<div class="container">
											<div class="col-md-1 col-lg-1">
												<div class="row">${message(code:'votes.label', default: 'Votes')}</div>
												<div>${subject.vote}</div>
											</div>
				
											<div class="col-md-1 col-lg-1">
												<div class="row">${message(code:'answers.label', default: 'Answers')}</div>
												<div>${subject.getAnswers().size()}	</div>
											</div>
											
											<div class="col-md-10 col-lg-10">
												<g:link controller="subject" action="show" id="${subject.id}"><h4>${subject.title}</h4></g:link>
												${subject.dateCreated}
											</div>
										</div>
									</li>
								</g:each>
							</ul>
						</div>
					</li>
				</g:if>
				
				<g:if test="${secUserInstance?.userAnswers}">
					<li class="fieldcontain">
						<h2 id="userAnswer-label"><g:message code="secUser.userAnswers.label" default="User Answers" /></h2>
						<div class="well">
							<ul class="list-unstyled homeSubjectList">
								<g:each in="${secUserInstance.userAnswers}" var="answer">
									<li class="homeSubjectListItem">
										<div class="container">
											<div class="col-md-1 col-lg-1">
												<div class="row">${message(code:'votes.label', default: 'Votes')}</div>
												<div>${answer.vote}</div>
											</div>

											<div class="col-md-10 col-lg-10">
												<small>On <g:link controller="subject" action="show" id="${answer.subject.id}">${answer.subject.title}</g:link> ${answer.dateCreated}</small>
												<br/>
												${answer.content}
											</div>
										</div>
									</li>
								</g:each>
							</ul>
						</div>					
					</li>
				</g:if>
			
				<g:if test="${secUserInstance?.userComments}">
					<li class="fieldcontain">
						<h2 id="userComments-label"><g:message code="secUser.userComments.label" default="User Comments" /></h2>
						<div class="well">
							<ul class="list-unstyled homeSubjectList">
								<g:each in="${secUserInstance.userComments}" var="comment">
									<li class="homeSubjectListItem">
										<div class="container">
											<div class="col-md-1 col-lg-1">
												<div class="row">${message(code:'votes.label', default: 'Votes')}</div>
												<div>${comment.vote}</div>
											</div>

											<div class="col-md-10 col-lg-10">
												<small>On <g:link controller="subject" action="show" id="${comment.answer.subject.id}">${comment.answer.subject.title}</g:link> ${comment.dateCreated}</small>
												<br/>
												${comment.content}
											</div>
										</div>
									</li>
								</g:each>
							</ul>
						</div>
					</li>
				</g:if>
			</ol>
		</div>
	</body>
</html>